---
deployment:
  tasks:
    - export DEPLOYPATH=/home/softuni1/staging.softuni.rs/wp-content/themes/divi-child/
    - /bin/rm -rf $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R ./* $DEPLOYPATH
